# -- Overrides the default release name
nameOverride: ""

# -- Overrides the full name of the release, affecting resource names
fullnameOverride: ""

infisical:
  # -- Enable Infisical chart deployment
  enabled: true
  # -- Sets the name of the deployment within this chart
  name: infisical

  autoBootstrap:
    # -- Enable auto-bootstrap of the Infisical instance
    enabled: false

    image:
      # -- Infisical Infisical CLI image tag version
      tag: latest

    # -- Template for the data/stringData section of the Kubernetes secret. Available functions: encodeBase64
    secretTemplate: '{"data":{"token":"{{.Identity.Credentials.Token}}"}}'

    secretDestination:
      # -- Name of the bootstrap secret to create in the Kubernetes cluster which will store the formatted root identity credentials
      name: "infisical-bootstrap-secret"

      # -- Namespace to create the bootstrap secret in. If not provided, the secret will be created in the same namespace as the release.
      # namespace: "default"

    # -- Infisical organization to create in the Infisical instance during auto-bootstrap
    organization: "default-org"

    credentialSecret:
      # -- Name of the Kubernetes secret containing the credentials for the auto-bootstrap workflow
      name: "infisical-secrets"

  databaseSchemaMigrationJob:
    image:
      # -- Image repository for migration wait job
      repository: ghcr.io/groundnuty/k8s-wait-for
      # -- Image tag version
      tag: no-root-v2.0
      # -- Pulls image only if not present on the node
      pullPolicy: IfNotPresent

  serviceAccount:
    # -- Creates a new service account if true, with necessary permissions for this chart. If false and `serviceAccount.name` is not defined, the chart will attempt to use the Default service account
    create: true
    # -- Custom annotations for the auto-created service account
    annotations: {}
    # -- Optional custom service account name, if existing service account is used
    name: null

  # -- Override for the full name of Infisical resources in this deployment
  fullnameOverride: ""
  # -- Custom annotations for Infisical pods
  podAnnotations: {}
  # -- Custom annotations for Infisical deployment
  deploymentAnnotations: {}
  # -- Number of pod replicas for high availability
  replicaCount: 2

  image:
    # -- Image repository for the Infisical service
    repository: infisical/infisical
    # -- Specific version tag of the Infisical image. View the latest version here https://hub.docker.com/r/infisical/infisical
    tag: latest
    # -- Pulls image only if not already present on the node
    pullPolicy: IfNotPresent
    # -- Secret references for pulling the image, if needed
    imagePullSecrets: []

  # -- Environment variables for Infisical pods
  env: []
  # -- Environment variables from Kubernetes secrets for Infisical pods
  envFrom: []

  # -- Kubernetes Secret reference containing Infisical root credentials
  kubeSecretRef: "infisical-secrets"

  # -- Startup probe for Infisical pods
  startupProbe:
    httpGet:
      path: /api/status
      port: 8080
    periodSeconds: 1
    failureThreshold: 60

  # -- Readiness probe for Infisical pods
  readinessProbe:
    httpGet:
      path: /api/status
      port: 8080
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 2
    timeoutSeconds: 5

  # -- Liveness probe for Infisical pods
  livenessProbe:
    httpGet:
      path: /api/status
      port: 8080
    periodSeconds: 10
    failureThreshold: 3

  # -- Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # -- Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  # -- Security context for Infisical pods
  securityContext: {}
  # -- Node affinity settings for pod placement
  affinity: {}
  # -- Tolerations definitions
  tolerations: []
  # -- Node selector for pod placement
  nodeSelector: {}
  # -- Topology spread constraints for multi-zone deployments
  # -- Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
  topologySpreadConstraints: []

  service:
    # -- Custom annotations for Infisical service
    annotations: {}
    # -- Service type, can be changed based on exposure needs (e.g., LoadBalancer)
    type: ClusterIP
    # -- Service port
    port: 8080
    # -- Service target port on container
    targetPort: 8080
    # -- Optional node port for service when using NodePort type
    nodePort: ""

  # -- Extra environment variables to set on the Infisical container. Useful for setting variables like NODE_EXTRA_CA_CERTS.
  # -- Example:
  # -- extraEnv:
  # --   - name: NODE_EXTRA_CA_CERTS
  # --     value: /etc/ssl/certs/ca-certificates.crt
  extraEnv: []

  resources:
    limits:
      # -- Memory limit for Infisical container
      memory: 1000Mi
    requests:
      # -- CPU request for Infisical container
      cpu: 350m

ingress:
  # -- Enable or disable ingress configuration
  enabled: true
  # -- Hostname for ingress access, e.g., app.example.com
  hostName: ""
  # -- Specifies the ingress class, useful for multi-ingress setups
  ingressClassName: nginx

  nginx:
    # -- Enable NGINX-specific settings, if using NGINX ingress controller
    enabled: false

  # -- Custom annotations for ingress resource
  annotations: {}
  # -- TLS settings for HTTPS access
  tls: []
    # -- TLS secret name for HTTPS
    # - secretName: letsencrypt-prod
    # -- Domain name to associate with the TLS certificate
    #   hosts:
    #     - some.domain.com

# Postgres Cluster
# https://cloudnative-pg.io/
cnpg:
  enabled: true

  dbUrlOptions: "?schema=infisical"

  cluster:
    name: infisical

    labels:
    annotations:

    spec:
      instances: 1

      bootstrap:
        initdb:
          database: infisical
          owner: infisical

      storage:
        size: 10Gi

      walStorage:
        size: 10Gi

  pooler:
    enabled: false
    instances: 1

    labels:
    annotations:

    type: rw

    pgbouncer:
      poolMode: transaction
      parameters:
        max_client_conn: "1000"
        default_pool_size: "10"

  backups:
    enabled: false

    labels:
    annotations:

    schedule: "0 0 0 * * *" # every day at midnight UTC
    retentionPolicy: "30d"

    # https://cloudnative-pg.io/plugin-barman-cloud/docs/object_stores/#s3-compatible-storage-providers
    # kubectl create secret generic cnpg-s3-creds -n infisical \
    #   --from-literal=ACCESS_KEY_ID=<access key here> \
    #   --from-literal=ACCESS_SECRET_KEY=<secret key here>
    config: {}
      # endpointURL: https://s3.us-west-002.backblazeb2.com
      # destinationPath: s3://infisical-cnpg/backups/local-dev/
      # s3Credentials:
      #   accessKeyId:
      #     name: cnpg-s3-creds
      #     key: ACCESS_KEY_ID
      #   secretAccessKey:
      #     name: cnpg-s3-creds
      #     key: ACCESS_SECRET_KEY

# Redis
# https://ot-redis-operator.netlify.app/docs/getting-started/standalone/
redis:
  enabled: true

  # deployment name
  name: infisical-redis

  labels: {}
  annotations: {}

  # https://ot-redis-operator.netlify.app/docs/crd-reference/api-reference/#redisspec
  kubernetesConfig:
    # https://quay.io/repository/opstree/redis?tab=tags&tag=latest
    image: quay.io/opstree/redis:v8.2.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 1Gi
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

# Misc extra k8s manifests to be deployed
extraManifests: []
  #
  # - apiVersion: apps/v1
  #   kind: Deployment
  #   metadata:
  #     name: my-deployment
  #     namespace: custom-namespace
  #   spec:
  #     replicas: 1
  #     template:
  #       spec:
  #         containers:
  #         - name: my-container
  #           image: my-image
  #           command: ["my-command"]
  #         restartPolicy: Never
