{{ if .Values.infisical.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infisical.fullname" . }}
  annotations:
    updatedAt: {{ now | date "2006-01-01 MST 15:04:05" | quote }}
    {{- with .Values.infisical.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "infisical.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.infisical.replicaCount }}
  selector:
    matchLabels:
      {{- include "infisical.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "infisical.matchLabels" . | nindent 8 }}
      annotations:
        updatedAt: {{ now | date "2006-01-01 MST 15:04:05" | quote }}
        {{- with .Values.infisical.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "infisical.serviceAccountName" . }}
      {{- with .Values.infisical.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.infisical.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.infisical.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.infisical.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.infisical.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.infisical.image.imagePullSecrets | nindent 6 }}
    {{- end }}
      containers:
      - name: {{ template "infisical.name" . }}-{{ .Values.infisical.name }}
        image: "{{ .Values.infisical.image.repository }}:{{ .Values.infisical.image.tag }}"
        imagePullPolicy: {{ .Values.infisical.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        # postgres
        {{- if .Values.cnpg.enabled }}
        - name: CNPG_URI
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.cnpg.cluster.name }}-postgres-app"
              key: "uri"
        - name: DB_CONNECTION_URI
          value: "$(CNPG_URI){{ .Values.cnpg.dbUrlOptions }}"
        {{- end }}

        # redis
        {{- if .Values.redis.enabled  }}
        - name: REDIS_URL
          value: "redis://{{ .Values.redis.name }}:6379"
        - name: REDIS_HOST
          value: {{ .Values.redis.name }}
        - name: REDIS_PORT
          value: "6379"
        {{- end }}

        {{- with .Values.infisical.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        envFrom:
        - secretRef:
            name: {{ .Values.infisical.kubeSecretRef }}
        {{- with .Values.infisical.envFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        {{- with .Values.infisical.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.infisical.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.infisical.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.infisical.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with  .Values.infisical.resources }}
        resources: {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.infisical.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      {{- with .Values.infisical.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "infisical.fullname" . }}
  labels:
    {{- include "infisical.labels" . | nindent 4 }}
  {{- with .Values.infisical.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.infisical.service.type }}
  selector:
    {{- include "infisical.matchLabels" . | nindent 8 }}
  ports:
    - protocol: TCP
      port: {{ default 8080 .Values.infisical.service.port }}
      targetPort: 8080
      {{- if eq .Values.infisical.service.type "NodePort" }}
      nodePort: {{ .Values.infisical.service.nodePort }}
      {{- end }}
{{ end }}
