{{- if .Values.redis.enabled }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.redis.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
# https://ot-redis-operator.netlify.app/docs/configuration/redis/
spec:
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  kubernetesConfig:
    {{- toYaml .Values.redis.kubernetesConfig | nindent 4 }}
  storage:
    {{- toYaml .Values.redis.storage | nindent 4 }}
{{- end }}
