name: Release Gateway Helm Chart
on:
    workflow_dispatch:

jobs:
    release-helm:
        name: Release Helm Chart
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Helm
              uses: azure/setup-helm@v3
              with:
                  version: v3.10.0

            - name: Install python
              uses: actions/setup-python@v4

            - name: Install Cloudsmith CLI
              run: pip install --upgrade cloudsmith-cli

            - name: Build and push helm package to CloudSmith
              run: cd helm-charts && sh upload-gateway-cloudsmith.sh
              env:
                  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
